name = "guesthouse-api"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
GALLERY_FOLDER = "dist/assets/gallery"

# Secrets (set via wrangler-action):
# - DB_HOST
# - JWT_SECRET
