name: Publish to GHCR
on:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          username: ${{ secrets.REPO_NAME }}
          password: ${{ secrets.GHCR_PAT }}
          registry: docker.pkg.github.com
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REPO_NAME }}/guesthouse:latest
