name: Publish to GHCR
on:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.REPO_NAME }}
          password: ${{ secrets.GHCR_PAT }}
          registry: docker.pkg.github.com
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REPO_NAME }}/guesthouse:latest
